### ISSUE TITLE
Prepare release 0.99.57

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/webextension_local_filesystem_links#101]
Coming from: https://github.com/feinstaub/webextension_local_filesystem_links/pull/99#issuecomment-357465182

The sign command works. There is one error though (and a few warnings).

Banned 3rd-party JS library

**Error: Your add-on uses a JavaScript library we consider unsafe. Read more: https://bit.ly/1TRIyZY
js/jquery-1.11.3.min.js**

Warning:
We allow and encourage an upgrade but you cannot reverse this process. Once your users have the WebExtension installed, they will not be able to install a legacy add-on.
The Function constructor is eval.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
app.js line 1 column 546
eval can be harmful.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
app.js line 1 column 576
The Function constructor is eval.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
app.js line 1 column 56083
Unsafe assignment to innerHTML

Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
app.js line 1 column 56490
Unsafe assignment to innerHTML

Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
app.js line 6 column 26463
The Function constructor is eval.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
app.js line 6 column 32888
The Function constructor is eval.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
options.js line 1 column 546
eval can be harmful.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
options.js line 1 column 576
The Function constructor is eval.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
options.js line 1 column 56610
Unsafe assignment to innerHTML

Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
options.js line 1 column 57017
Unsafe assignment to innerHTML

Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
options.js line 6 column 26463
The Function constructor is eval.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
options.js line 6 column 33166
The Function constructor is eval.

Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
options.js line 6 column 52503
Known JS library detected

Warning: JavaScript libraries are discouraged for simple add-ons, but are generally accepted.
js/jquery-1.11.3.min.js

**Comment by feinstaub** [comment]
I also had to change the addon's ID. I'll commit that now.

When I upload the final zip file, I now only get the banned JavaScript library error.

**Comment by AWolf81** [comment]
OK, I've updated jQuery to 2.2.4 from Google CDN [here](https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js).

I've also tested jquery-observe with the new jQuery version and it's working as before. Please re-check if the error is fixed.

I have to re-create the binaries of the native app because of the id change. I'm creating the new files now.

**Comment by feinstaub** [comment]
The signing worked. It created the file firefox_webextension_local_filesystem_links-0.99.57-an+fx.xpi.

I uploaded it and now is claiming the old id is the correct one. I changed the ID.

Interestingly, now the sign command fails with:

```
Building web extension from /home/dev/src/firefox_addon_local_filesystem_links/feinstaub/dist
Validating add-on [........................................................................................................................................................................................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/fe6c77baae9345fa916d006be1a03e86
Your add-on has been submitted for review. It passed validation but could not be automatically signed because this is a listed add-on.
FAIL
```

So I skipped the signing and uploaded the zip file. This seemed to succeed with these messages:

```
WebExtension upgrade

We allow and encourage an upgrade but you cannot reverse this process. Once your users have the WebExtension installed, they will not be able to install a legacy add-on.
Porting a legacy Firefox add-on on MDN
Add-on submission checklist

Please verify the following points before finalizing your submission. This will minimize delays or misunderstanding during the review process:

    Include detailed version notes (this can be done in the next step).
    If your add-on requires an account to a website in order to be fully tested, include a test username and password in the Notes to Reviewer (this can be done in the next step).

The validation process found these issues that can lead to rejections:

    The Function constructor is eval.
    Unsafe assignment to innerHTML
```

**Comment by AWolf81** [comment]
OK, so signing is not needed to submit the extension?

Is the ID now the old one? Should I revert the binaries to the previous version? Or is it possible to change to the new ID?

**Comment by feinstaub** [comment]
I just got an email that the addon was approved. Apparently the sign command automatically triggers the review process. No need to upload it manually.

**Comment by feinstaub** [comment]
I committed the changed ID. Maybe, you would have to adapt the binaries.

**Comment by AWolf81** [comment]
Yes, I've tested the extension from Mozilla Gallery and I need to change to the previous ID. 

At the moment it's not working because the ID is important for the native messaging to work.

**Comment by feinstaub** [comment]
Time to have the first firework (🎆) for having the new version in the Gallery after 10 month after the last version! :-)

**Comment by feinstaub** [comment]
Thanks Alex for your commitment to the addon!

**Comment by AWolf81** [comment]
You're welcome. I'm also glad that the new version is released.

The native host app installer files are reverted to previous version. But I have a new problem with Avira VirusScanner, it now shows HEUR/APC (Cloud) detected. 

I need to check why this is triggered now. Scans that happened yesterday always passed.

![grafik](https://user-images.githubusercontent.com/3046542/34960217-3f74b0aa-fa3a-11e7-8c6d-bfbe8c04472f.png)

**Comment by MurzNN** [comment]
Please provide in Extension description text on Mozilla website - info that it need to install external application, and link to page with instruction how to install native application. For prevent issues like https://github.com/feinstaub/webextension_local_filesystem_links/issues/103

**Comment by MurzNN** [comment]
And I have an error on installing in Ubuntu 16.04 AMD64:
```$ ./install_host_compiled.sh 
./install_host_compiled.sh: 42: ./install_host_compiled.sh: Bad substitution
```

**Comment by AWolf81** [comment]
**Installation error:**
I'll check the line [install_host_compiled.sh#L42](https://github.com/feinstaub/webextension_local_filesystem_links/blob/master/native-host/build/linux/install_host_compiled.sh#L42) later today.

Maybe it's sh related. I think it's working if your calling the file with `$ bash ./install_host_compiled.sh`.
I'll change the Shebang in the sh file to `#!/bin/bash` that should fix the bad substitution error. I have to do some debugging if there is a different error in that line.

**Comment by MrWillow** [comment]
AWolf81 / Alex: Thank you very much for the new version!

**Comment by feinstaub** [comment]
> Please provide in Extension description text on Mozilla website - info that it need to install external application, and link to page with instruction how to install native application. For prevent issues like #103

@MurzNN: I added a note to the addons description: "NOTE for previous users: Starting with Firefox 57, the addon requires you to install an additional helper application. Otherwise the addon cannot function properly. The details are explained in a first-run dialog when you install the addon." (https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links)

**Comment by feinstaub** [comment]
16.01.2018 I received a review comment which has to be answered in 7 days:

```
Before a complete review can be carried out, please provide the following information within the next 7 days:

1) This version contains obfuscated, minified, concatenated or otherwise machine-generated code. Please provide the original sources, together with instructions on how to generate the final XPI. Source code must be provided as an archive and uploaded using the source code upload field, which can be done during submission or on the version page in the developer hub.

Please read through the instructions at https://developer.mozilla.org/en-US/Add-ons/Source_Code_Submission. If sources have not been provided within 7 days, this version will be rejected and removed from our queues.
More Information: https://blog.mozilla.org/addons/2016/04/05/improved-review-time-with-links-to-sources/

Established libraries (eg: JQuery, bootstrap) do not require the inclusion of their sources.
Please use non-custom versions of jquery-ui, as well as the stock version of jquery and others, that match the original checksums on the maintainer&#39;s website.
```

@AWolf81 Do we have any such machine-generated code except for standard libraries?

**Comment by AWolf81** [comment]
@feinstaub We're having machine generated code for these javascript files - 
app.js, background.js, content.js and options.js.

I haven't verified if the hash for jQuery & jQuery-observe are matching the checksum of the maintainers page. jQuery file is new because of the update to version 2.x and jQuery-observe is unchanged and the same file as in version 0.99.47.

`npm run build` is generating code into the dist folder. It's minified code.

Please upload the source code as [zip file](https://github.com/feinstaub/webextension_local_filesystem_links/archive/0.99.57.zip) or maybe add github link as source (if possible or not already added as info) and take the info from [this](https://github.com/feinstaub/webextension_local_filesystem_links/issues/95#issuecomment-355782008) comment as "guide" for creating the extension files for production.

**Comment by feinstaub** [comment]
Thanks. I provided the information to Mozilla.

**Comment by MurzNN** [comment]
About `bad substitution` error - yes, changing `sh` to `bash` fixes the problem, so if I start via `$ bash ./install_host_compiled.sh` - installs successfully.

**Comment by AWolf81** [comment]
We can close this as the next version is ready and the bad substiution issue is also fixed in the latest native app bundle.
