### ISSUE TITLE
Virus scanner alerts

### ISSUE THREAD

**Issue by AWolf81** [feinstaub/webextension_local_filesystem_links#102]
There are some virus scanners that are reporting a virus/malware alert for `local-messaging-host.exe`.

I'd like to state the messages here:
- <del>atc4.detection detected by BitDefender</del> Should be working now
- <del>heur/apc (cloud) detected by Avira</del> Virus definition update happened today and not it's working. 20.01.2018
- Security risk detected: WS.Reputation.1 (unproven origin, few users, very new) detected by Symantec Endpoint Protection (should be better after code signing (still open))

[VirusTotal](https://www.virustotal.com/#/url/3a3cc3efd7249df539fa9917774938b3c191ed9f4b502b617e0534528f8c5f8e/detection) 0 scanner from 66 scanners detected a Virus. (Last analysis 2018-01-17 01:06:58 UTC)

**Work-arounds**
In Bitdefender add the file as exception. <del>For Avira there is no work-around at the moment. Adding the file as exception wasn't working for me. I've filed a false positive report for the file at Avira - I'll add an update if it's added to the exception list at Avira.</del>
It seems that Avira added the file into virus definition file on my request - definition update today fixed the quarantine of the file.

**Comment by JupiterJonesJJ** [comment]
Symantec Endpoint Protection reports this when I try to run the file:
Security risk detected: WS.Reputation.1 (unproven origin, few users, very new)

Is this somehow related to the (missing?) certificate?

**Comment by AWolf81** [comment]
Thanks for reporting. 

Yes, I think this is related to the missing certificate. I'm still waiting for my code signing hardware to improve this. Once I've received it, I can sign the installer & the application file - tracked in issue #100.

**Comment by AWolf81** [comment]
@PeterZamudio As you mentioned during development you've had problems with Bitdefender. Can you please file a false-positive report [here](https://www.bitdefender.com/submit/) for the file `local-link-messaging-host.exe`? 
I did the same for Avira AntiVir CloudScanner.

Please add the info here if you're getting a feedback from Bitdefender to the report. VirusTotal doesn't report any problems. 
But it's only virus detection - so heuristic problems can still occur.

**Comment by PeterZamudio** [comment]
@AWolf81 
false-positive report by Bitdefender is done. Still testing and it seems fine now. 
Look forward to seeing the finished product.

**Comment by AWolf81** [comment]
@PeterZamudio Thanks for reporting to Bitdefender.

Version 0.99.57 is available in Mozilla Store. But there are still some points to improve especially Windows installation & code signing.

**Comment by PeterZamudio** [comment]
@AWolf81
Hi again. Thanks so much, its great now its up and working. I just want to report in with a few minor problems for the fine tuning if it's posible.
1. When I start Firefox the links are not imedialy active. I have to click once on reload page then it works.
2. When I leave the Firefox open for some time the Links become inactive and I have to click again on reload page.
3. Sometimes it goes mad and open 2 or 3 or 5 or ..... times the same program. Restarting Firefox solves the problem.
All minor problems, mostly it works great :-)
Thanks again
Peter

**Comment by AWolf81** [comment]
@PeterZamudio You're welcome and thanks for reporting the issues. Can you please open a new issue for 1. and 2.?

I have some questions to them:
1. Is the problem only on the first page that's loaded by Firefox after start e.g. opening a default homepage?
2. Is it on every page with local links? How long is inactivity time? Are just the direct links not working then? Is the folder icon still present and clickable?
3. I know this issue (related to #108 & issue #113) and should be improved in the next version. I'm still working on this because opening a local html page in browser is still problematic - not fixed yet.

**Comment by AWolf81** [comment]
Closing this as the Virus alerts should be fixed.
