### ISSUE TITLE
Bug with Local Filesystem 0.99.57

### ISSUE THREAD

**Issue by LaurentDSI** [feinstaub/webextension_local_filesystem_links#103]
Since this morning Local Filesystem 0.99.47 is upgrade in 0.99.57.

When we try to open a folder and  we receive this message : Attempt to postMessage on disconnected port. Please chech that you have installer the native app. See installation guide addon-bar menu.

We are using : Firefox ESR 52.5.3 (32 bits)

I try to reinstall 0.99.42 or 0.99.47 and it's work fine.

Do you have a solution with the new version ?

Best regards

**Comment by AWolf81** [comment]
Yes, click in the extension bar menu at "Show install info..."
![grafik](https://user-images.githubusercontent.com/3046542/34987737-8c71ffe8-fabc-11e7-878b-abacd8d8e7b3.png)

Then download the native app for your operating system and install the app.
![grafik](https://user-images.githubusercontent.com/3046542/34987814-c7f0c202-fabc-11e7-8db1-6698a91c44e9.png)

The app is needed to make the extension compatible with FF >= 57.  We'll add that info to the Mozilla store so everyone knows how to use the extension. This helps for new installations but not for updated versions.

There are no new features in the new version but we're trying to implement all features from 0.99.47. So I think it's OK to stay at the version 0.99.47 if you're using the older version of FF. But we are not maintaining the old addon anymore - so no new features/fixes will be added there.

This is also a breaking change for the whitelist setting as the new extension requires a different match pattern (see info in the install info).

**Comment by FransGoos** [comment]
we have since this morning the same problem as LaurentDSI with the disconnected port. We use firefox 56....  I have tested the add-on in Firefox 57... and we had the same problem. Downgrading to the previous version of this add-on did work

**Comment by MrWillow** [comment]
@FransGoos  Did you install the program? The new local filesystem links CANNOT do its job without it.
Read AWolf81's comment on how to install it. Note: This only works for Linux and Windows at the moment.

**Comment by FransGoos** [comment]
Yes @MrWillow. We have installed the add on in firefox in a windows environment. We have tested the add-on in firefox 57 and firefox 56, but in Firefox 57 the add-on is not working

We have tested the links in IE11 and there they are working. So the links are good.
frans
Frasn

**Comment by MrWillow** [comment]
@FransGoos That is a shame. 
I tested on FF 57.0.4 (64bit) on Windows 10 Home edition, and that works all OK. 
Just to be sure, you DID also install: native-app-setup.exe ?

**Comment by asig2016** [comment]
Installing version 0.99.57 (including native-app-setup.exe) on Windows 7 Professional on a user with Administration rights is working fine. But the same Procedure on the same box but on a simple user account instead gives me also the same error (when trying to open a folder):

Attempt to postMessage on disconnected port. Please chech that you have installer the native app. See installation guide addon-bar menu.

**Comment by AWolf81** [comment]
@asig2016 Thanks for the info.

I've only tested on Windows 10 Pro and there it doesn't require admin rights to install the app. But maybe for Windows 7 it is more restricted and adding the registry key for the current user requires elevated rights.

OK, I see a possible problem. The app is installed on a per-user basis into user's home directory and if you're installing the app with admin rights the app is only available for the admin user. I need to check if installing at Windows 7 with-out admin rights is possible. If that's not possible as you've mentioned, maybe the system-wide installation helps (option not added to the installer yet) - see issue #105.

**Comment by FransGoos** [comment]
@MrWillow I contacted our system administrator. First the users are also working in Windows 7 prof. Furthermore our administrator asked more info on the native-app-setup.exe. Is this something for Firefox or for the add-on? Or have you other information that can be useful?

**Comment by AWolf81** [comment]
Closing as the issue should be fixed.
If it's still a problem we can re-open the issue.
