### ISSUE TITLE
alien local filesystem links

### ISSUE THREAD

**Issue by FransGoos** [feinstaub/webextension_local_filesystem_links#104]
We are using the add local filesystem links in version 0.99.47. We cannot use the newest version 0.99.57 because the links are not working here.
In this version some users (not all) receive the message: alien-local-filesystem-links  ERROR_BAD_LINK.
I have seen an other old, closed issue with the same error message. But there it had to do with ~
The link that we use is the following:
file:///X:/Sites/nen/documentLibrary/Content/2018/1/15/n-0120dc23-ab68-412f-a660-22ca449a7b68/ASTM_F3141_-_17a_en.pdf 
The link works in IE11 in the URL box
hope that there is a solution or advise
Frans

**Comment by feinstaub** [comment]
Finally, I we achieved the big goal to migrate the addon to the new WebExtension API. We wanted to provide users who use Firefox 57+ with the new version as soon as possible. Now that users start to use the new addon, issues like your's arise. Please, consider using the old addon for some time until all major glitches are fixed.

Meantime, bug reports on the new version are welcome.

**Comment by AWolf81** [comment]
@FransGoos Could you fix your issue? For me it's not clear what's not working. The link looks valid and it should open the file. Are all links not working? Or is it just the mentioned link?

The message that's shown for links that are not found is: Couldn't open file ...
ERROR_BAD_LINK was displayed in a previous version of the addon.

**Comment by AWolf81** [comment]
Closing this issue.
If it's still a problem we can re-open it.
