### ISSUE TITLE
Bug with file://// (4-slashes link)

### ISSUE THREAD

**Issue by SebSDW** [feinstaub/webextension_local_filesystem_links#106]
First a big thank you for the update to FF57 !!

Then, a little problem appeared after this update, file links to other computers like _file:////192.168.x.y/folder/file.txt_  that used to work with previous version don't work anymore, I got a 'Error could not open file...'

I can indeed access the files using a regular explrer, so I know the file is reachable...

Any hint ?

**Comment by AWolf81** [comment]
You're welcome and thanks for reporting the issue.

Yes, you're right. I've missed to add [line 48-52 from launch-local-process of version 0.99.47](https://github.com/feinstaub/webextension_local_filesystem_links/blob/0.99.47/lib/launch-local-process.js#L48).

Sorry, for that but that's fix quickly. I'll push the native app today or tomorrow. Just an update at the native app required to fix this.
I've only tested the correct 5-slash UNC link but not the 4-slash version. I've added an additional test page so I don't miss this next time and your link should work with the new version.

I'll send you a comment here once I've pushed the binary.

**Comment by AWolf81** [comment]
Updating is a bit delayed because I'd like to publish the next version with code signing. But certificate is not available yet.

I think it should be ready early next week.

**Comment by SebSDW** [comment]
Perfect, thanks for the feedback !

**Comment by AWolf81** [comment]
@SebSDW I've uploaded the new version 0.2.1 of the native app with 4-slash link support. 

Still with-out code signing because no response from cert. agency - I need to call them because they're not responding to my e-mails.

So I'll close this. If something is not working, please add a comment and I'll check it.

**Comment by SebSDW** [comment]
@AWolf81 thank you !
