### ISSUE TITLE
Native app in Linux

### ISSUE THREAD

**Issue by robinstridh** [feinstaub/webextension_local_filesystem_links#107]
Hi,

I have installed the Local Filesystem Links addon in Firefox 57.0.4 on Ubuntu 16.04, but clicking a local link yields:
"Error: Attempt to post message on disconnected port"
Surely this is because the native-host program is missing.
I have downloaded the file for the native app, but I cannot find an installer inside. I also tried to download the source from GitHub and build myself, but I cannot find any documentation on how to install it.

Best regards,
Robin

**Comment by AWolf81** [comment]
Hi Robin:
Please have a look at my installation advice at issue #103. There is also a link to the archived Linux installation script.
You may have to start the script with `bash ./install_host_compiled.sh` this should install the native app.

**Comment by robinstridh** [comment]
It works now. Thanks!

**Comment by AWolf81** [comment]
OK, we can close this. 

I've change the shebang for the install script to bash so `./install_host_compiled.sh` is working in Ubuntu.
