### ISSUE TITLE
Folder Icon does not open the file folder, please help.

### ISSUE THREAD

**Issue by Everstill** [feinstaub/webextension_local_filesystem_links#111]
Hi, 

Thanks for the update! I have updated the addon, running into a problem, the yellow holder icon won't open the file folder instead it opens a few folders link to "This PC" & "Documents", the destination should be in our network server, could someone let me know how I can fix this?

**Comment by AWolf81** [comment]
Can you please show me your link tag?
Is it with 5-slashes after file? `<a href="file://///servername/share/">example</a>`
Note: 4-slashes are supported in the next version of the native app.

**Comment by Everstill** [comment]
Hi,

Thanks for reply! Yes I copied the link, this is a 4-slashes. Does that mean I have to wait till next version of native app? Or is there anyway to change it? Thanks!

file:////FOREST_HOST/Data/M....

**Comment by AWolf81** [comment]
You can wait for the new version. Should be ready this week.

Or you can change to a link with 5-slashes if you can change the link. The new version can handle both types.

**Comment by AWolf81** [comment]
@Everstill New version 0.2.1 of native app is available with 4-slash UNC link support.

So we can close this.
