### ISSUE TITLE
Bug in settings of add on : open link / open directory interchanged (German version)

### ISSUE THREAD

**Issue by Ralf77** [feinstaub/webextension_local_filesystem_links#112]
In the settings of the German version the radio button for "open link" enables opening the directory and the option for "open directory" leads to opening the file link. So the functionality is misleadingly interchanged.
Tested with Firefox version 57.0.4 (64bit)

![filelink_bug](https://user-images.githubusercontent.com/35593596/35210127-3b0586b8-ff51-11e7-8ba2-2be943c35884.PNG)

**Comment by AWolf81** [comment]
Don't know what you mean. I think it is working correctly.

If "Link direkt öffnen" is selected a click on the link text of a file will open that file directly and the folder symbol will open the containing folder.

If "Beinhaltenden Ordner öffnen" is selected a click on the link text will open the containing directory and the symbol close to the link (arrow symbol) will open the file.

**Please notice:** After changing the settings you have to reload the page to show the updated settings - not applied immediately. That will be improved in a future version.

**Comment by Ralf77** [comment]
OK, I didn't realize that the functionality is meant to work this way. I thought that the folder icon has the same functionality as the link.
 
In Firefox 45.7 and version 0.99.41 (01/2016) the usage of the folder icon in our application had the same impact as if clicking on a link.
After the update to Firefox 57.0.4 and the current version the behavior changed as you described.
