### ISSUE TITLE
whitelisted URLs. Matching problem

### ISSUE THREAD

**Issue by MrWillow** [feinstaub/webextension_local_filesystem_links#115]
I am very happy with the ability to whitelist, but I cannot get it working over here.

We use our mainweb application (Only hosted on our intranet) on addresses that start like this:
**http://MyServerName:82/somepath/somescript**

So I tried in the whitelist URLs:
**http://MyServerName:82/***
and
**http://MyServerName:*/***

But in both cases it disables the Local Filesystem Links functionality. 
So it seems my pattern isn't OK.

How can I make our URLs match?

----------------------------------------------
Addition:
After browsing I found a dependency in package.json: "match-pattern": "0.0.2"

Which is documented here, I think:
https://developer.chrome.com/extensions/match_patterns

I am looking into it now.... LATER: No, that document doesn't shed any light on my issue.
Does anybody know a solution to limit to http://MyServerName:82/* ?

**Comment by AWolf81** [comment]
I think  it should work with-out the port: `http://MyServerName/*`.

I tested it with Confluence at `servername:8090` and the extension was active there. But in Confluence there seems to be a problem with the icon of the extension. Not visible in Confluence. I need to check this later.

But I only have Confluence at work - so it's difficult to test but maybe I find some time to do more debugging.

**Comment by MrWillow** [comment]
Thank you Alex!
That did the trick.

**Comment by AWolf81** [comment]
You're welcome.
Maybe I'm adding an info into a guide so others also know how to add it.
