### ISSUE TITLE
links are not immediately active and deactivate after a period of time.

### ISSUE THREAD

**Issue by PeterZamudio** [feinstaub/webextension_local_filesystem_links#116]
@AWolf81
    _**When I start Firefox the links are not immediately active. I have to click once on reload page then it works.**_
This problem is when I start Firefox and it happens every time. Tested on 15 PCs, all the same.
I tried clearing the cache and its still the same.
   
   _**When I leave the Firefox open for some time the Links become inactive and I have to click again on reload page.**_
This problem again happens on all 15 PCs. How long it takes exactly I don't know. I would guess 30 minutes plus. 

Both problems are small and only a detail.

**Comment by AWolf81** [comment]
@PeterZamudio Thanks for reporting.

OK, starting issue will be fixed in the next version. I've added an event handler to check the homepage on browser window creation.

The other issue is difficult to test but I'll try and keep a session open for some time (> 30 min.). Is the folder icon still present and just the link click event is not working or is also reveal click not working?

**Comment by PeterZamudio** [comment]
@AWolf81
The folder icon vanishes after the time out (> 30 min.)
Click on reload or F5 and it's back.

**Comment by AWolf81** [comment]
I couldn't re-create that behaviour yet. 
Do I have to leave the window with that single tab open for more than 30 Min.?

During my test I minimized the window with the page but maybe this changes the effect.

**Comment by PeterZamudio** [comment]
I always have several tabs open and never minimize. When I am working I have often 10 or more programs running and maybe 5 or 6 tabs open in Firefox. I am sorry I can't say exactly when or why it happens. It's a very small problem anyway because with 1 click on reload or F5 and they are back. I can live with it no problem. I just thought you would like to know it happens. The extention is still great as it is :-) you did a fantastic job.

**Comment by AWolf81** [comment]
Thanks, good to hear that you like the new extension as it is now.

OK, noticed and it's great that you reported it - so I know that the problem exists. And I understand that it's a bug that's hard to detect. If I can re-produce it I'll try to fix it. 

It's also good to know that the icon will be removed after that time so I can check the points in code that could trigger accidentally the removal of the icon. 

If you see it next time can you please also check if the folder icon is gray in addon bar - not sure if this info helps to debug but this would be also interesting.

I'm fixing the other open points first and check this later as this is just a small bug.

**Comment by AWolf81** [comment]
@PeterZamudio The links should be immediately active after opening the browser in version 0.99.59.

Can you please check if the other issue with deactivation after 30 minutes is still present? I couldn't re-create that behavior.

**Comment by PeterZamudio** [comment]
Will do. I can comfirm the links are immediately active now after opening the browser. I will get back to you about if they are deactivating after a period time or not.

**Comment by PeterZamudio** [comment]
@AWolf81 Its working fine now. left it running for 2 days and it didn't once loose the Links. Great work, well done :-)

**Comment by AWolf81** [comment]
@PeterZamudio Thanks for your feedback.

I'll close this issue. If something is not working please let me know.
