### ISSUE TITLE
How to install additional helper application?

### ISSUE THREAD

**Issue by Peter0** [feinstaub/webextension_local_filesystem_links#117]
There is stated: "Starting with Firefox 57, the addon requires you to install an additional helper application. Otherwise the addon cannot function properly. The details are explained in a first-run dialog when you install the addon."

I have installed LFL years ago. Should I deinstall it and install again, only to get the mentioned details?

Where can I find the explanation how to install the helper application?

**Comment by AWolf81** [comment]
Please have a look at issue #103. 
You can access the link by clicking on the folder icon in the addon bar.

You're right the information will be shown only at first installation - maybe I can also show this info once at an update. But I haven't added that yet.

**Comment by Peter0** [comment]
Thanks. Seems to work.

**Comment by Peter0** [comment]
Another Question: Also yesterday, before installing native app., LFL seems to work, but only for a short period after reload a page.
Is this behaviour sensible when there is no native app.?

**Comment by Peter0** [comment]
sorry, accidently closed

**Comment by Peter0** [comment]
Since I have installed the native app, there seems to be no problems anymore regarding this issue.
