### ISSUE TITLE
Whitelist internal domain with port number, but without TLD

### ISSUE THREAD

**Issue by Peter0** [feinstaub/webextension_local_filesystem_links#118]
I want to whitelist "```http://example-abc:8080/*```" to enable our internal domain with pages like
    ```http://example-abc:8080/example/projects/Wiki```
I tried "```http://example-abc:8080/*```", "```*://example-abc:8080/*```", "```http://example-abc*```" and so on, but I managed to let LFL work only if I use a plain "```*```" as whitelist.

Thanks for any directions on how to choose whitelists.

**Comment by AWolf81** [comment]
Please have a look at issue #115.

I haven't added that info in a description yet. I need to check where I can add it. Maybe I'll add a help section to the addon menu.

**Comment by AWolf81** [comment]
Added the info to the post-install page. I think that's OK for now. I'll think about the help section later.

**Comment by Peter0** [comment]
Thanks, seems to work.
