### ISSUE TITLE
Saving whitelist swallows key strokes

### ISSUE THREAD

**Issue by Peter0** [feinstaub/webextension_local_filesystem_links#119]
When editing whitelist, the content seems to be saved regulary in a seconds-timescale. Every save action seems to swallow simultaneous key strokes. Annoyingly, editing whitelist without looking on the screen therefore ends up with garbled input.
Maybe an explicit save command, like a button, is a smarter solution.

**Comment by AWolf81** [comment]
OK, thanks for reporting. 

I'll check this. 
Maybe I can increase debounce time a bit.

**Comment by AWolf81** [comment]
Can you please create an animated gif (e.g. with [ShareX](https://getsharex.com/)) to show me that behavior? Maybe I'm typing slower or faster but I couldn't re-create it. 
For me this is working and every keystroke is added in the input.

**Comment by Peter0** [comment]
It seems to be a slightly other problem.
When entering a slash, the input box loses focus in favour of the "search all add-ons" on top of page.
This happens typical, when entering "http://…". To input the second slash, I have to click in the whitelist-textbox again.
I tried different typing speeds. Contrary to what I've written in my OP, there seems to be no timing relation.

**Comment by AWolf81** [comment]
@Peter0 Is this issue with the second slash still happening in the latest version?
I couldn't re-create the issue. I'm not losing focus during typing. 
I've tried many variations (slow typing, fast typing, stopping at first slash and then continue typing,. ..)

**Comment by Peter0** [comment]
Regarding 0.99.62 from May, 23.

My suggestion: Editing white list is a rather singular event. Editing is possible, if one keeps an eye on the cursor/focus. It seems you can't reenact this behaviour, which leads me guessing that there is an environment-specific dependency, which is difficult to track down.
My suggestion: For the time being, let us this ticket go sleeping.
