### ISSUE TITLE
Deprecation of jQuery 2.x in Firefox add-ons

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/webextension_local_filesystem_links#123]
On 15.02.2018 22:02, Firefox Add-ons Team wrote:
> Hello,
> 
> You’re receiving this message because you’re an add-on developer registered on AMO
> (addons.mozilla.org)
> and and you are using jQuery 2.x in at least one of your add-ons. We want to inform you about the
> upcoming deprecation of that version.
> 
> jQuery 2.x is no longer maintained and contains vulnerabilities that could lead to security issues
> in add-ons. Effective immediately, the validation process will warn you if jQuery 2.x is found
> during the submission of a new version or add-on. After September 1, 2018, no new submissions using
> jQuery 2.x will be accepted.
> 
> Please upgrade to jQuery 3.x as soon as possible. Refer to the upgrade guide at
> https://jquery.com/upgrade-guide/3.0/
> for more information.
> 
> Regards,
> 
> The Add-ons Team

**Comment by AWolf81** [comment]
We can close this because I've updated to JQuery 3.x.
