### ISSUE TITLE
postmessage on disconnected port

### ISSUE THREAD

**Issue by rsenio** [feinstaub/webextension_local_filesystem_links#124]
Issue has been around for a while, when using newer versions of Firefox the addon simply does not work, even with the "helper" application installed.

**Comment by AWolf81** [comment]
Thanks for reporting the issue.

Can you please give me some details so I can debug the issue?
I'd like to know the following points:
- Operating system + version
- Helper app installed as administrator or as standard user?
- Helper app installed for the user that's using the extension
- Installed version of the helper app (at the moment, only displayed in the windows installer)
- Have you tried to install C++ re-distributable from the installer (if you're using Windows)?

At the moment, I'm working on the installer for the helper app (also called native app) to improve the installation.
With the next version a system-wide installation will be supported but that requires administrator rights. But I think for most users it's OK to install the app for the current user only. 

For the current version there could be a problem if you're installing the app as administrator and use it with a different user account.

**Comment by rsenio** [comment]
You may be correct, when standard users get the UAC prompt to install the helper app. I didn't know they were able to install it.

**Comment by AWolf81** [comment]
Closing as the helper app should work as expected.

If it's still an issue please let me know.
