### ISSUE TITLE
No detection of links when loading page in frame

### ISSUE THREAD

**Issue by rimeco** [feinstaub/webextension_local_filesystem_links#128]
The extension works fine on "normal" pages, but when a page initiates a load in a frame of that page the present links are not detected. Reloading the frame doesn't help. If the page in the frame is loaded separately (in a new tab or window), detection works fine. (FF59.0.2 - ext. v.0.99.57 or 0.99.60 on WIN10)

**Comment by AWolf81** [comment]
Thanks for reporting the issue.

I know iframe handling is not perfect and needs some improvement. E.g. the following fiddle runs in an iframe http://jsfiddle.net/awolf2904/tefcs74q/ and works on initial load but after reloading the content of the iframe - the links stop working. Can be tested in the fiddle - just click run and the links are disapearing.

I have to do more tests to check how to improve iframe handling. 

This could be related to the disabled mutation observer - no javascript added links are working at the moment. See issue #109.

**Comment by AWolf81** [comment]
Closing this issue as there is another issue for it.

I will add my feedback there.
