### ISSUE TITLE
optionally build URL using two slashes only

### ISSUE THREAD

**Issue by MrMonaco** [feinstaub/webextension_local_filesystem_links#13]
Dear australiensun,

I hoped to use your addon to open search results created by MS Search Server Express.
MS-sytax ist two slashes, but your tool replaces them wih three
thus "file://myserver/subdi/filename.doc" becomes "file:///myserver/subdi/filename.doc" and the link will not work :-(
Any chances for a quick "fix".

Thank you very much in advance

**Comment by feinstaub** [comment]
Thanks for providing a patch.  I already did a similar fix with 23be8146e13c7f49d5fbdbef267479e41378251c. Does this solve your issue?

If you not, you extend to the test suite page test/webserver/std1/issue.htm to reproduce the desired behaviour.

About getting an XPI: I updated the README.md with some instructions.

**Comment by feinstaub** [comment]
Yes, a test case would be appreciated.
