### ISSUE TITLE
cant install in firefox v60

### ISSUE THREAD

**Issue by ketnoe** [feinstaub/webextension_local_filesystem_links#131]
need this to work or a replacement for firefoxv60, and developers edition.

thanks

**Comment by feinstaub** [comment]
A new version is online. Please try again and reopen this ticket if you still cannot install it.

**Comment by ketnoe** [comment]
Got the addon installed.. now i'm getting this error, 
"Attempt to postMessage on disconnected port.  Please check that you have installed the native app.  See installation guide in addon-bar menu"

I've gone through everything and cant seem to figure that part out.  I did install another addon called Nate Messaging Open Letter, but I dont think thats related.. 

thanks
