### ISSUE TITLE
firefox developer v60 

### ISSUE THREAD

**Issue by ketnoe** [feinstaub/webextension_local_filesystem_links#132]
Got the addon installed.. now i'm getting this error,
"Attempt to postMessage on disconnected port. Please check that you have installed the native app. See installation guide in addon-bar menu"

I've gone through everything and cant seem to figure that part out. I did install another addon called Nate Messaging Open Letter, but I dont think thats related..

thanks

**Comment by AWolf81** [comment]
Please have a look at issue #129 (similar question) and the installation guide of the native app.

**Comment by AWolf81** [comment]
Closing this issue as there is a similar question.
