### ISSUE TITLE
The extension is not parsing some links

### ISSUE THREAD

**Issue by JHonru** [feinstaub/webextension_local_filesystem_links#133]
A few days ago I've detected that some of the links pointing to the internal server of my company are not being parsed by the extension. The little file icon that should be appearing on the right side of the link it's not visible anywhere.
The link's urls are like this file://///<Internal Server>/<Directory Route>
The page where they're located on is a jsp based webpage. Could it be related to this issue?

**Comment by AWolf81** [comment]
Closing this as link parsing should work.
If the issue still exists we can re-open it.
