### ISSUE TITLE
Incompatible with firefox quantum

### ISSUE THREAD

**Issue by bkkwok** [feinstaub/webextension_local_filesystem_links#136]
On the main page for firefox addons https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/ says that the add on is not compatible with firefox quantum.  Does not allow me to download.

I go to the local filesystem links version history: https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/versions/  tried to download version 0.99.47, and computer says the file is corrupt.

**Comment by AWolf81** [comment]
Thanks for reporting.

Not sure why the file 0.99.47 is corrupt. But the old version is not working with FF Quantum.

We had a Quantum compatible version 0.99.61 but it was removed by AMO review team (see issue #127). Fixing this issue is not that easy - still looking for a solution.

**Comment by feinstaub** [comment]
The addon was removed again because be did not fully sort out the issue yet.

**Comment by AWolf81** [comment]
@bkkwok New FF Quantum compatible version 0.99.62 is online. Please check if everything is working.

(We're now waiting for the feedback from Mozilla review team for the build issue. But this should work now.)

**Comment by AWolf81** [comment]
Closing this as the new version is online with-out removal by AMO team.
