### ISSUE TITLE
Trojan.Bitrep!8.F596 (RDM+:cmRtazrEL35Erk9fkSj4Q0uDQhdR)

### ISSUE THREAD

**Issue by billydanielcom** [feinstaub/webextension_local_filesystem_links#140]
native-app-setup.exe
This appears to be a false positive -unable to confirm safe.
Any help appreciated?
Scanned File virustotal.com (Rising 1 of 67 who scanned file) found Trojan.
https://www.virustotal.com/#/file/44c36f2be56e8d115703abf2110a2694758f8b26d88c1b8fe7f550f67199df74/detection

**Comment by AWolf81** [comment]
Seems like Rising is not reporting the Trojan false-positive anymore.
Revisited Virustotal today.
Closing this for now - If there are still problems we can re-open this.
