### ISSUE TITLE
Windows Defender: Threat detected

### ISSUE THREAD

**Issue by turtle0x1** [feinstaub/webextension_local_filesystem_links#141]
Hi I can see other anti-virus software has flageed the installable as a virus, threat detector is now also flagging the .exe

You can see this bellow (sorry for the poor image quality)

![image001](https://user-images.githubusercontent.com/12494629/42557283-f1d4e0ae-84e5-11e8-8f45-e7a41415e513.jpg)

![image002](https://user-images.githubusercontent.com/12494629/42557285-f37ad648-84e5-11e8-861b-65badbedfb08.jpg)

**Comment by haary** [comment]
Confirmed, at 
[Virustotal](
https://www.virustotal.com/#/file/c47a017655cef0f95b835750c909d9ad2e67205884c0c62f0dc7a881a372f0d4/detection)

14 AV scanners detected this file als malicious

**Comment by AWolf81** [comment]
I think we can close this. There is one false-positive from Sophos ML on Virustotal.

Maybe I'll check if it's possible to report it at Sophos ML.
