### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by TimatRush** [feinstaub/webextension_local_filesystem_links#151]
I'm trying to install this extension, and I get this message: Installation aborted because the add-on appears to be corrupt.

Using Firefox 66.0 - Any ideas?

**Comment by AWolf81** [comment]
Not sure what's wrong.

I've tested it and it works for FF 68.0.1 on Windows 10.

- What OS do you use? 
- Can you try a newer FF version but v66.0 should also work?
- Other extensions can be installed without any problem?

**Comment by TimatRush** [comment]
Unfortunately I'm locked into version 66. I work on a VDI where the administrator rights keep me pretty limited. It's Windows 7. I've been able to install other extensions, yes, though the selection of ones I've tried has been somewhat limited.

**Comment by AWolf81** [comment]
OK, I've tested the extension installation in FF 66.0 and it installed without a problem on Windows 10.

Not sure if it's related to Win7 and I don't have a VM image for Win7 at the moment - so it's difficult to test.

Maybe the following [post](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/comment-page-6/#comment-226171) could help.
But it mentions different versions to be affected by the issue.

**Comment by TimatRush** [comment]
That did it. Thanks so much!
