### ISSUE TITLE
Google sheets reports a script in this extension is causing firefox to slow down

### ISSUE THREAD

**Issue by grahamj157** [feinstaub/webextension_local_filesystem_links#164]
environment 
OS win 10
BROWSER firefox 87.0 (64-bit)

I attempted to temporarily disable the extension from the Google sheet tab but this didnt to work 

on my LMDE4 64 bit pc running firefox 78.9.0esr, i have no problem.
let me know if i can help by providing more focused information

**Comment by AWolf81** [comment]
I couldn't recreate this issue with FF 113.0.1 (64-Bit) on Windows 10.

I know this is an old issue. 
If this is still a problem, please let me know. Also, a link to a document with the issue would help.

Closing this for now but we can re-open it if this is still an issue.
