### ISSUE TITLE
Firefox Link gone?

### ISSUE THREAD

**Issue by EngKarl** [feinstaub/webextension_local_filesystem_links#217]
Hey!
The Firefox Link is down. Is their a possibility to get this online again or get the zip to download it and install it on my own in Firefox?
LG Karl

**Comment by AWolf81** [comment]
@EngKarl yes, sorry, during a review, Mozilla had a complain - see other issue.

Sorry for the inconvenience. Seems like they disabled it.

We're working on it.

If this is taking too long, I could check for a zip file. But I'm expecting it back in a week or two.

**Comment by EngKarl** [comment]
@AWolf81 Thank you for your answer! Its completely ok, that it will be online in a few weeks again!

**Comment by AWolf81** [comment]
@EngKarl It's [back](https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/). Review issue is resolved.

Everything should work as before. 
If anything is not working, please let me know.

(I'm closing this.)
