### ISSUE TITLE
AMO reviewer requested Privacy policy

### ISSUE THREAD

**Issue by AWolf81** [feinstaub/webextension_local_filesystem_links#218]
@feinstaub can you please check and add the privacy policy that I have added to the repo as markdown.

It's generated by ChatGPT and I have reviewed it.
IMO, it's OK.

I can not add the policy because only the owner can add it.

I think the issue #217 is related to this.

Hopefully it's OK after adding this. Because I'm already writing with the guys at Mozilla for around two weeks.

Initially, they complained about the minified code but I supplied the source code as zip.

Next, they had issues with Linux build from source which I couldn't reproduce.

**Comment by feinstaub** [comment]
Yes, I saw the previous mailings. I added the privacy policy. Hopefully the pending issues can be resolved.

**Comment by feinstaub** [comment]
And thanks for your work! :+1: :-)

**Comment by AWolf81** [comment]
@feinstaub you're welcome and thanks for adding the privacy policy.

The extension is back in the gallery, so we can close this issue.
