### ISSUE TITLE
Installation of helper application

### ISSUE THREAD

**Issue by ukw100** [feinstaub/webextension_local_filesystem_links#221]
After reinstalling local filesystem links, the addon no longer displays the link of the helper application. The window "Important! Next steps required...." no longer appears. But the helper application can no longer be reinstalled without a link.

It would be desirable to be able to display this page again at any time via the addon settings.

**Comment by AWolf81** [comment]
@ukw100 I think there is an issue with the click handler on the extension icon.

A click on the icon should show the link to open the "install info" (see screenshot below).

But the popover sometimes is not showing. After several clicks it will open.
It's difficult to debug the issue as the popover will work after some clicks.

Maybe it's a good idea to also add the link to the "install info" to the extensions settings page.

![image](https://github.com/feinstaub/webextension_local_filesystem_links/assets/3046542/8ced30c1-e9d8-4165-abb5-bc9c020e288b)

**Comment by ukw100** [comment]
You wrote:
> Maybe it's a good idea to also add the link to the "install info" to the extensions settings page.

Yes, that would be helpful. I think the issue can be closed. Thank you very much for this great addon!
