### ISSUE TITLE
Change extension id / name

### ISSUE THREAD

**Issue by WileC** [feinstaub/webextension_local_filesystem_links#86]
Change the extension id / name from "jid1-JAzC7z53jemo5Q@jetpack" to a better readable one, like "localfilesystemlink" or any other like this.

**Comment by feinstaub** [comment]
could be done with #81

**Comment by AWolf81** [comment]
I close this as I think that the ID is not freely selectable as it's registered at Mozilla gallery to the extension.

And I think that it can't be changed for an existing extension. See Publishing [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID)

I'm also not seeing a benefit of having a readable ID.

**Comment by feinstaub** [comment]
+1 from my side to keep the issue closed
