### ISSUE TITLE
cannot open unc path with new versions

### ISSUE THREAD

**Issue by Kaor** [feinstaub/webextension_local_filesystem_links#88]
We use Local Filesystem Links for opening HTML files in Firefox.
UNC Path are like : file://///COMPUTERNAME/directory/file.html
it don't work with Version 0.99.47, Version 0.99.46,
but works very well with Version 0.99.42
Firefox 52.0.2
Windows 7 pro
thanks for this great plugin

**Comment by feinstaub** [comment]
Thanks for the report and good to hear that it is helpful to you. I don't use Windows. So I cannot reproduce it. Maybe @AWolf81 can confirm this bug.

**Comment by AWolf81** [comment]
I can't see that issue with version 0.99.47 with my UNC test link of my NAS - tested with FF 52.0.2 (32bit) on Windows 10 Pro. Your link looks good with 5 slashes.

What message does the addon show? Just file not found notification? Or is only the link to the HTML file a problem?

Maybe I can see something by comparing 0.99.42 and 0.99.47, but that's probably difficult. It would be easier to debug if i could re-create the behavior.

**Comment by AWolf81** [comment]
I'm closing this. If the issue is still present in latest version please add a comment.
