### ISSUE TITLE
Cannot access UNC top level folder?

### ISSUE THREAD

**Issue by glyphmon** [feinstaub/webextension_local_filesystem_links#90]
The addon appears to work fine for folders and files contained within the top level of the server, for example:
**\\server\myfolder**
correctly opens and displays the folder "myfolder" on our server "server".

The functionality I was looking for was to be able to use a link to:
**\\\server\\**
to browse all shared folders and printers on the server.  The rationale is that I'm creating some self-help pages served by an internal web server and one of the topics (I'm sure there will be more) was adding a printer from the print server.

When I try to click on such a link I get the error "Couldn't open file file://///server/".  Is this capability supported somehow and simply requires different coding of the anchor tag in the HTML or is this not possible due to some file system/API weirdness?

**Comment by AWolf81** [comment]
Thanks for filing the issue & sorry for the late answer.

I also see that issue. Not sure why this happens. I have to do more tests but I'm pretty busy with the migration to webextension at the moment.
The behavior will be the same with the web extension.

Once the migration is done, I'll check if this can be fixed.

**Comment by AWolf81** [comment]
I've fixed that in the latest native app (v0.2.1) not published yet for web extension 0.99.57. 

I had to change directory check because Python doesn't properly check existence with `os.path.exists` for UNC paths. I've used the error code of `net view //servername/` to check existence of UNC path. (Trailing slash after server name can be added but also works with-out it.)

**Comment by AWolf81** [comment]
I'll close this as the new version 0.2.1 is available. 

Please check the new version and top level UNC links should work as expected.
