### ISSUE TITLE
this does not work with Firefox on Mac OS X - suggest URL change

### ISSUE THREAD

**Issue by ghost** [feinstaub/webextension_local_filesystem_links#91]
For the local filebrowser ( on a Mac that is the Finder )  to be able to find the resource of an URL the syntax file:/// or file://// or file:///// does not work. This is simply undefines. The add-on in FF on a Mac hands the url simply as file:///// over to the Finder, which is undefined.

file:// is the url to local files, remote files need the right protocol in the url such as smb:// ...

In case the url consists of file://///....... which links to a remote share the url has to be converted into smb://....

In Windows the url file:///// should also give an error because that does NOT link to a local file. However such an url does work miraculously. I assume the distinction between local and remote files is weak or fuzzy under Windows. Whatever. 

So what we would need to make the add-on work on FF on Mac  is to change the url accordingly.
That should be easy by asking the browser on what OS it does work. When it says "Mac" just switch to another output format of the url.

**Comment by AWolf81** [comment]
It's possible to do things differently for mac os but for me it's not possible because I can only test on Windows or Linux.

But you can fork the addon and improve mac support. (But please notice that there will be a larger change to the addon - transfer to WebExtension because Addons

**Comment by AWolf81** [comment]
will be deprecated soon.)

Sorry, for this comment split. I'm on my mobile and can't edit comments here.

**Comment by AWolf81** [comment]
@katematsuda Can you please have a look at version 0.99.57?
You can download the native app for Mac [here](https://github.com/AWolf81/webextension_local_filesystem_links-native-host-binaries/tree/master/mac).

The link to the native app in post installation page will be added with the next extension version.

File links are working - SMB still not supported. I have to check how I can add it.

**Comment by AWolf81** [comment]
Mac should be supported. Please let me know if it's still an issue.
