### ISSUE TITLE
When activated, Firefox ignores mimetype "application/xml", maybe more

### ISSUE THREAD

**Issue by NicolasGoeddel** [feinstaub/webextension_local_filesystem_links#92]
Hi,

I often use the ability of Firefox to nicely show XML files. This always works if the mimetype of the downloaded XML is "application/xml". If I activate your addon and open such a XML file Firefox only shows the Textnodes of the XML without any tags, line breaks and folding features.

I don't know if yout addon also affects other things like this.

I am using Firefox 54.0.1 (32-Bit) on Windows and version 0.99.47 of your plugin.

**Comment by AWolf81** [comment]
Hi,

thanks for reporting this issue. 

I've tested the following link https://www.w3schools.com/xml/simple.xml with addon active and the XML display is not working. Seems like the addon is replacing the XML view.

But at the moment I'm not sure why and where this happens. I need to do more research and maybe I have to add a file type check to disable the Addon if it's a XML file.

**Comment by AWolf81** [comment]
OK, this will be fixed in the next release.

I've excluded XML files to avoid the mentioned behavior. It affected the XML view because the extension created a HTML page instead of the XML view.

@feinstaub Can you please mark this for the next release?

**Comment by feinstaub** [comment]
Hi Alex, can't you manage milestones? If not, please create an issue with title "Version 0.99.58" or similar and place links to the issues which you plan for this version there.
